bluejay-battery: only overlay battery replacement strings for bluejay
In the stock OS, these battery replacement strings are present for every device  except for oriole
and raven.

oriole and raven don't have the new battery replacement strings in SystemUIGoogle and
SettingsGoogle. This results in adevtool / arsclib running into an error as it won't be able to find
those strings for oriole and raven:

Error: unexpected stderr
SystemUIGoogleSyntheticOverlay: missing string entries: [battery_management_action,
battery_replacement_early_notify_des, battery_replacement_notify_des,
battery_replacement_notify_help_url, battery_replacement_notify_title]
SettingsGoogleSyntheticOverlay: missing string entries: [battery_tip_early_replacement_summary,
charge_cycle_count]

For simplicity, move these new strings to be bluejay-exclusive for now.

This could make UI testing for the battery replacement notification and tip on non‑bluejay devices a
bit inconvenient. (Obviously testing the functionality of the battery tip should be done on bluejay
only for affected and unaffected devices.)